OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Building
    Domain: building.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Photovoltaic
    Domain: photovoltaic.example.com
    Template:
      Count: 1
    Users:
      Count: 1