version: '3.7'

services:
  trading.example.com:
    container_name: trading.example.com
    working_dir: /home/server
    image: node:8
    volumes: 
      - ./trading:/home/server
    command: sh -c 'yarn && yarn start:nodemon'
    ports: 
      - 3001:3000
    environment: 
      MYSQL_DATABASE: trading
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
  mysql.example.com:
    image: mysql:5.7
    container_name: mysql.example.com
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: trading
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password