version: "3.7"

services:
  fabric.example.com:
    container_name: fabric.example.com
    working_dir: /home/server
    image: node:8
    volumes:
      - ./fabric-server-nest:/home/server
    command: sh -c 'yarn && yarn start:nodemon'
    environment:
      GOPATH: /home/server/artifacts
      MYSQL_URL: mysql.example.com
      MYSQL_DATABASE: fabric
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      SMARTCONTRACT_URL: smartcontract.example.com:5000
      BUILDING_ADMIN_USERNAME: admin
      BUILDING_ADMIN_PASSWORD: adminpw
      PV_ADMIN_USERNAME: admin
      PV_ADMIN_PASSWORD: adminpw
      UTILITY_ADMIN_USERNAME: admin
      UTILITY_ADMIN_PASSWORD: adminpw
    ports:
      - 3000:3000
  mysql.example.com:
    image: mysql:5.7
    container_name: mysql.example.com
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fabric
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
volumes: 
  mysql: