version: '3.7'

services: 
  jupyter.example.com:
    container_name: jupyter.example.com
    image: jupyter/scipy-notebook
    volumes: 
      - ./jupyter:/home/jovyan/work
    ports: 
      - 8888:8888