version: '3.7'

services:
  fabric.example.com:
    container_name: fabric.example.com
    working_dir: /home/server
    image: node:8
    volumes: 
      - ./fabric-server-nest:/home/server
    command: sh -c 'yarn && yarn start:nodemon'
    environment: 
      GOPATH: /home/server/artifacts
    ports: 
      - 3000:3000