version: '3.7'

services:
  biddingstrategy.example.com:
    container_name: biddingstrategy.example.com
    build: ./bidding-strategy
    volumes: 
      - ./bidding-strategy:/home/bidding-strategy
    command: flask run --host 0.0.0.0
    environment: 
      FLASK_APP: src/app.py
      FLASK_DEBUG: 1
      GOPATH: 
    ports: 
      - 8080:5000