version: '3.7'

services:
  smartcontract.example.com:
    container_name: smartcontract.example.com
    build: ./smart-contracts
    volumes: 
      - ./smart-contracts:/home/smartcontract
    command: flask run --host 0.0.0.0
    environment: 
      FLASK_APP: src/app.py
      FLASK_DEBUG: 1
      GOPATH: 
    ports: 
      - 5000:5000