version: '3.7'

services:
  fabric-nest.example.com:
    container_name: fabric-nest.example.com
    working_dir: /home/server
    image: node:8
    volumes: 
      - ./fabric-server-nest:/home/server
    command: sh -c 'yarn && yarn start:nodemon'
    ports: 
      - 3000:3000