version: '3.7'

services:
  fabric-express.example.com:
    container_name: fabric-express.example.com
    working_dir: /home/server
    image: node:8
    volumes: 
      - ./fabric-server-express:/home/server
    command: sh -c 'yarn && node app'
    environment: 
      PORT: 4000
    ports: 
      - 4000:4000