version: '3.7'

services: 
  smartcontract.example.com:
    volumes: 
      - ./smart-contracts:/home/smartcontract
    command: flask run --host 0.0.0.0
    environment: 
      FLASK_APP: src/app.py
      FLASK_DEBUG: 1
    ports: 
      - 5000:5000
  jupyter.example.com:
    container_name: jupyter.example.com
    image: jupyter/scipy-notebook
    volumes: 
      - ./jupyter:/home/jovyan/work
    ports: 
      - 8888:8888
  fabric.example.com:
    volumes: 
      - ./fabric-server:/server
    command: sh -c 'cd /server && yarn && yarn start:dev'
    ports: 
      - 3000:3000